# Generated by Django 3.0.3 on 2020-02-25 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(choices=[('HR', 'HR'), ('DEV', 'DEV'), ('SALE', 'SALE'), ('MARKETING', 'MARKETING'), ('TESTER', 'TESTER'), ('AI', 'AI')], default='DEV', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('staffs', models.ManyToManyField(to='company.Staff')),
            ],
        ),
    ]
