# Generated by Django 3.0.3 on 2020-02-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='number_staff',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='number_project',
            field=models.IntegerField(default=1),
        ),
    ]
