# Generated by Django 3.0.3 on 2020-02-25 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200225_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number_project',
        ),
    ]
