# Generated by Django 3.0.3 on 2020-02-27 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_project_number_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='number_staff',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.Department'),
        ),
    ]
