# Generated by Django 3.0.3 on 2020-02-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200227_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='revenue',
            field=models.FloatField(default=None),
        ),
    ]
