# Generated by Django 3.0.3 on 2020-02-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_project_revenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_related_name': 'project_set'},
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='staffs',
            field=models.ManyToManyField(related_name='project_set', to='company.Staff'),
        ),
    ]
